#!/bin/bash
# =============================================================================
# Nightshift Droplet Setup Script
# Module: nightshift
#
# This script sets up a fresh Ubuntu 24.04 droplet with:
# - Security hardening (non-root user, SSH lockdown, fail2ban)
# - Required packages (Python 3.12, Node.js, Claude CLI)
# - Git configuration for automated push/pull
# - Claude CLI for AI task execution
#
# Usage:
#   ssh root@<droplet-ip> 'bash -s' < 01-droplet-setup.sh
#
# IMPORTANT: Run this as root on first connection. After completion,
# you will only be able to connect as the 'deploy' or 'gregor' user.
# =============================================================================

set -e

# Configuration
DEPLOY_USER="deploy"
ADMIN_USER="gregor"
SSH_PORT="22"
DATA_REPO="git@github.com:gregregoryo/Data.git"

# Admin SSH public keys
ADMIN_SSH_KEY="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC6xOraJQU40sUxUAfFrnFT8180l5CNG6Ld92JKbviXTQRxJnZsH3015GDIBrnBFJP1saLcRstjzOKS8Kqvsy6YwhNzbTbSw1U1UlDziuiiNes+tHHNsbIIYy7jrxOVr+73hGBfWUsuZ8nczoRlZHAapP8O6YV8QSREpyXJh1P/v6x7ejm9ufstOv/DrWtEXGFv8dBxpN/29WnVQd6jZfWg2xB2CQNr2gzFpFnCFZzsTTyDuF2MYEr6xl6WG13KH3ZDzm+sevAA3s8m94BoR1xx81O6W+WXGpth3ND9HI03zv4CP3KQ0SrulLu+6FT/Bkw2JDHzgJ9apUiYfeWrXDEKmA0WfveBufHcxQe7kdZp5j9CLNbaD9JA/IWIaNqlLt0FlHv5k9etq7+1pxbjaDJXLMYFXp0J0T/W5h+rptSiVZJLI+p5AWi/BVo6mm4xnokDKOsn2Gwcr+uZaejhmtayOsmwK7S0IlICavWk9lDGQSvyBqrzgnxJqkR2Ess1nhURCr1tBW8yx6o2pOVghJx2iCPrekW+2edCKOoADDCnenPjwYwvuSey5owXi8vaHN/M5RBew3JszDh8TEkLVK4mecVhkN0+AZdO6sL+ICpKrBOpXRDLReeCOaTy5xfE0uTAt7AOSv9/ohCnM+sROfzJ4TrW6/H7/72BrfmaPWcBpw== gregor@plur.si"
ADMIN_SSH_KEY_ED25519="ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMfqcXvUDBW73uMba/+Ha4Zm6i+YwqIP2VSQT5rmXJT8 gregor@ethswarm.org"

# Deploy key (for git operations)
DEPLOY_KEY_PUB="ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFa6oK6ES9dZZhI6orsfm+AtioToscoJinNjJ3QiFyUU datacore-deploy"

echo "=========================================="
echo "Nightshift Module - Secure Droplet Setup"
echo "=========================================="
echo ""

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    echo "ERROR: This script must be run as root"
    exit 1
fi

# =============================================================================
# PHASE 1: System Updates
# =============================================================================
echo "[Phase 1/7] Updating system packages..."
apt update && apt upgrade -y
apt autoremove -y

# =============================================================================
# PHASE 2: Create Deploy User
# =============================================================================
echo "[Phase 2/7] Creating deploy user with sudo access..."

if ! id "$DEPLOY_USER" &>/dev/null; then
    useradd -m -s /bin/bash "$DEPLOY_USER"
    usermod -aG sudo "$DEPLOY_USER"
    echo "$DEPLOY_USER ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/$DEPLOY_USER
    chmod 440 /etc/sudoers.d/$DEPLOY_USER

    mkdir -p /home/$DEPLOY_USER/.ssh
    if [ -f /root/.ssh/authorized_keys ]; then
        cp /root/.ssh/authorized_keys /home/$DEPLOY_USER/.ssh/
    fi

    chown -R $DEPLOY_USER:$DEPLOY_USER /home/$DEPLOY_USER/.ssh
    chmod 700 /home/$DEPLOY_USER/.ssh
    chmod 600 /home/$DEPLOY_USER/.ssh/authorized_keys 2>/dev/null || true

    echo "  - User '$DEPLOY_USER' created with sudo access"
else
    echo "  - User '$DEPLOY_USER' already exists"
fi

# Create admin user
echo "  - Creating admin user '$ADMIN_USER'..."
if ! id "$ADMIN_USER" &>/dev/null; then
    useradd -m -s /bin/bash "$ADMIN_USER"
    usermod -aG sudo "$ADMIN_USER"
    echo "$ADMIN_USER ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/$ADMIN_USER
    chmod 440 /etc/sudoers.d/$ADMIN_USER

    mkdir -p /home/$ADMIN_USER/.ssh
    echo "$ADMIN_SSH_KEY" > /home/$ADMIN_USER/.ssh/authorized_keys
    echo "$ADMIN_SSH_KEY_ED25519" >> /home/$ADMIN_USER/.ssh/authorized_keys

    chown -R $ADMIN_USER:$ADMIN_USER /home/$ADMIN_USER/.ssh
    chmod 700 /home/$ADMIN_USER/.ssh
    chmod 600 /home/$ADMIN_USER/.ssh/authorized_keys

    echo "$ADMIN_USER:$(openssl rand -base64 32)" | chpasswd

    echo "  - Admin user '$ADMIN_USER' created"
else
    echo "  - Admin user '$ADMIN_USER' already exists"
fi

# =============================================================================
# PHASE 3: SSH Hardening
# =============================================================================
echo "[Phase 3/7] Hardening SSH configuration..."

cp /etc/ssh/sshd_config /etc/ssh/sshd_config.backup.$(date +%Y%m%d)

cat > /etc/ssh/sshd_config.d/hardened.conf << 'EOF'
# Security hardened SSH configuration
# Generated by nightshift-module setup script

PermitRootLogin no
PasswordAuthentication no
PermitEmptyPasswords no
ChallengeResponseAuthentication no
KerberosAuthentication no
GSSAPIAuthentication no
Protocol 2
MaxAuthTries 3
MaxSessions 5
LoginGraceTime 30
ClientAliveInterval 300
ClientAliveCountMax 2
X11Forwarding no
AllowAgentForwarding yes
AllowTcpForwarding no
LogLevel VERBOSE
AllowUsers deploy gregor
EOF

if sshd -t; then
    systemctl reload sshd
    echo "  - SSH hardening configuration applied"
else
    echo "ERROR: SSH config test failed"
    exit 1
fi

# =============================================================================
# PHASE 4: Install Security Tools
# =============================================================================
echo "[Phase 4/7] Installing security tools..."

apt install -y ufw fail2ban unattended-upgrades apt-listchanges

# Configure UFW
ufw default deny incoming
ufw default allow outgoing
ufw allow $SSH_PORT/tcp comment 'SSH'
ufw allow 8080/tcp comment 'Health Check'
ufw --force enable

# Configure fail2ban
cat > /etc/fail2ban/jail.local << EOF
[DEFAULT]
bantime = 1h
findtime = 10m
maxretry = 3
banaction = ufw

[sshd]
enabled = true
port = $SSH_PORT
filter = sshd
logpath = /var/log/auth.log
maxretry = 3
bantime = 24h
EOF

systemctl enable fail2ban
systemctl restart fail2ban

# Configure unattended upgrades
cat > /etc/apt/apt.conf.d/50unattended-upgrades << 'EOF'
Unattended-Upgrade::Allowed-Origins {
    "${distro_id}:${distro_codename}";
    "${distro_id}:${distro_codename}-security";
};
Unattended-Upgrade::AutoFixInterruptedDpkg "true";
Unattended-Upgrade::MinimalSteps "true";
Unattended-Upgrade::Remove-Unused-Kernel-Packages "true";
Unattended-Upgrade::Remove-Unused-Dependencies "true";
Unattended-Upgrade::Automatic-Reboot "false";
EOF

cat > /etc/apt/apt.conf.d/20auto-upgrades << 'EOF'
APT::Periodic::Update-Package-Lists "1";
APT::Periodic::Unattended-Upgrade "1";
APT::Periodic::AutocleanInterval "7";
EOF

systemctl enable unattended-upgrades
systemctl start unattended-upgrades

# =============================================================================
# PHASE 5: Install Application Dependencies
# =============================================================================
echo "[Phase 5/7] Installing application dependencies..."

apt install -y curl git python3 python3-pip python3-venv jq htop netcat-openbsd

# Install Node.js 20 LTS
curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
apt install -y nodejs

# Install Claude CLI
npm install -g @anthropic-ai/claude-code

echo "  - Node.js: $(node --version)"
echo "  - npm: $(npm --version)"
echo "  - Python: $(python3 --version)"

# =============================================================================
# PHASE 6: Configure Git and Clone Repository
# =============================================================================
echo "[Phase 6/7] Configuring git for deploy user..."

# Set up deploy key for git operations
sudo -u $DEPLOY_USER mkdir -p /home/$DEPLOY_USER/.ssh

# The deploy private key will need to be added manually or via secure transfer
cat > /home/$DEPLOY_USER/.ssh/config << 'EOF'
Host github.com
    HostName github.com
    User git
    IdentityFile ~/.ssh/deploy_key
    IdentitiesOnly yes
EOF

chown -R $DEPLOY_USER:$DEPLOY_USER /home/$DEPLOY_USER/.ssh
chmod 600 /home/$DEPLOY_USER/.ssh/config

# Configure git
sudo -u $DEPLOY_USER git config --global user.email "nightshift@datacore.one"
sudo -u $DEPLOY_USER git config --global user.name "Nightshift Bot"
sudo -u $DEPLOY_USER git config --global pull.rebase true
sudo -u $DEPLOY_USER git config --global push.autoSetupRemote true

echo "  - Git configured for deploy user"
echo "  - NOTE: You need to manually add the deploy private key to /home/$DEPLOY_USER/.ssh/deploy_key"

# =============================================================================
# PHASE 7: Create Environment File Template
# =============================================================================
echo "[Phase 7/7] Creating environment file template..."

mkdir -p /home/$DEPLOY_USER/config
cat > /home/$DEPLOY_USER/config/nightshift.env << 'EOF'
# Nightshift Environment Variables
# Fill in the ANTHROPIC_API_KEY before running nightshift

# Required
ANTHROPIC_API_KEY=

# Optional
NIGHTSHIFT_DATA_DIR=/home/deploy/Data
NIGHTSHIFT_LOG_LEVEL=INFO
EOF

chown -R $DEPLOY_USER:$DEPLOY_USER /home/$DEPLOY_USER/config
chmod 600 /home/$DEPLOY_USER/config/nightshift.env

# =============================================================================
# FINAL SUMMARY
# =============================================================================
echo ""
echo "=========================================="
echo "Setup Complete!"
echo "=========================================="
echo ""
echo "SECURITY CHANGES APPLIED:"
echo "  - Created user: $DEPLOY_USER (with sudo)"
echo "  - Created admin: $ADMIN_USER (with sudo + SSH keys)"
echo "  - Root SSH login: DISABLED"
echo "  - Password auth: DISABLED (SSH keys only)"
echo "  - Firewall: ENABLED (SSH, 8080 only)"
echo "  - Fail2ban: ENABLED (24h ban after 3 failed attempts)"
echo "  - Auto security updates: ENABLED"
echo ""
echo "INSTALLED:"
echo "  - Node.js: $(node --version)"
echo "  - npm: $(npm --version)"
echo "  - Python: $(python3 --version)"
echo "  - Claude CLI: $(claude --version 2>/dev/null || echo 'installed')"
echo ""
echo "=========================================="
echo "IMPORTANT: NEXT STEPS"
echo "=========================================="
echo ""
echo "1. TEST SSH ACCESS (from another terminal):"
echo "   ssh deploy@$(curl -s ifconfig.me)"
echo "   ssh gregor@$(curl -s ifconfig.me)"
echo ""
echo "2. COPY DEPLOY KEY (from local machine):"
echo "   scp ~/.datacore/env/credentials/deploy_key deploy@$(curl -s ifconfig.me):~/.ssh/deploy_key"
echo "   ssh deploy@$(curl -s ifconfig.me) 'chmod 600 ~/.ssh/deploy_key'"
echo ""
echo "3. CLONE DATA REPO (as deploy user):"
echo "   ssh deploy@$(curl -s ifconfig.me)"
echo "   git clone $DATA_REPO ~/Data"
echo ""
echo "4. SET ANTHROPIC_API_KEY:"
echo "   nano ~/config/nightshift.env"
echo ""
echo "5. INSTALL SYSTEMD TIMERS:"
echo "   sudo cp ~/Data/.datacore/modules/nightshift/server/*.service /etc/systemd/system/"
echo "   sudo cp ~/Data/.datacore/modules/nightshift/server/*.timer /etc/systemd/system/"
echo "   sudo systemctl daemon-reload"
echo "   sudo systemctl enable nightshift-today.timer nightshift-overnight.timer"
echo "   sudo systemctl start nightshift-today.timer nightshift-overnight.timer"
echo ""
echo "WARNING: Root login is now DISABLED."
echo "Make sure you can login as 'deploy' or 'gregor' before closing this session!"
echo ""
